steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/reddit-extension-backend:$COMMIT_SHA'
      - '.'
    id: Build Image
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/reddit-extension-backend:$COMMIT_SHA'
    id: Push Image
    waitFor: ['Build Image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - reddit-extension-backend
      - '--platform=managed'
      - '--region=us-central1'
      - '--image=gcr.io/$PROJECT_ID/reddit-extension-backend:$COMMIT_SHA'
      - '--allow-unauthenticated'
    id: Deploy
    waitFor: ['Push Image']

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  diskSizeGb: 100
  substitutionOption: ALLOW_LOOSE

images:
  - 'gcr.io/$PROJECT_ID/reddit-extension-backend:$COMMIT_SHA'
